version: 0.0
os: linux
files:
  - source: /spring-boot-application.jar
    destination: /home/ec2-user/spring-boot-application.jar
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
